apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: resillience-comparision
build:
  artifacts:
  - image: springfactorialservice
    context: springfactorialservice
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - springfactorialservice/deployment.yaml
    - httpbin/deployment.yaml
    - fortio/deployment.yaml

