apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: resillience-comparision
build:
  artifacts:
  - image: git.fh-muenster.de:4567/lv-grewe/mwi/fep/fep22/service-meshes/resilience-comparison/springfactorialservice
    context: springfactorialservice
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - springfactorialservice/deployment.yaml
    - httpbin/deployment.yaml
    - fortio/deployment.yaml
