apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: resillience-comparision
build:
  artifacts:
  - image: micronautfactorialservice
    context: micronautfactorialservice
    docker:
      dockerfile: Dockerfile
  - image: micronautncrservice
    context: micronautncrservice
    docker:
      dockerfile: Dockerfile
  - image: springfactorialservice
    context: springfactorialservice
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - micronautncrservice/deployment.yaml
    - micronautfactorialservice/deployment.yaml
    - springfactorialservice/deployment.yaml
