apiVersion: v1
kind: Service
metadata:
  name: springfactorialservice
spec:
  selector:
    app: springfactorialservice
  ports:
  - name: http-springfac 
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  type:  ClusterIP #LoadBalancer (minikube tunnel erforderlihc)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springfactorialservice-deployment
  labels:
    app: springfactorialservice
    version: v1
spec:
  selector:
    matchLabels:
      app: springfactorialservice
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: springfactorialservice
        version: v1
    spec:
      containers:
      - name: springfactorialservice
        image: git.fh-muenster.de:4567/lv-grewe/mwi/fep/fep22/service-meshes/resilience-comparison/springfactorialservice
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
