apiVersion: v1
kind: Service
metadata:
  name: springfactorialservice
  annotations:
    mesh.traefik.io/circuit-breaker-expression: "ResponseCodeRatio(500, 600, 0, 600) > 0.20 || LatencyAtQuantileMS(50.0) > 200"
spec:
  selector:
    app: springfactorialservice
  ports:
  - name: http-springfac 
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  type:  ClusterIP #LoadBalancer (minikube tunnel erforderlihc)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springfactorialservice-deployment
  labels:
    app: springfactorialservice
    version: v1
spec:
  selector:
    matchLabels:
      app: springfactorialservice
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: springfactorialservice
        version: v1
    spec:
      containers:
      - name: springfactorialservice
        image: springfactorialservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080