apiVersion: v1
kind: Service
metadata:
  name: springfactorialservice
spec:
  selector:
    app: springfactorialservice
  ports:
  - name: http-springfac 
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  type:  ClusterIP #LoadBalancer #oder ClusterIP (dann minikube tunnel nicht erforderlich)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springfactorialservice-deployment
  labels:
    app: springfactorialservice
    version: v1
spec:
  selector:
    matchLabels:
      app: springfactorialservice
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: springfactorialservice
        version: v1
    spec:
      containers:
      - name: springfactorialservice
        image: springfactorialservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
